-- MySQL Script generated by MySQL Workbench
-- Seg 03 Jul 2017 21:14:29 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roteiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roteiro` (
  `id` INT NOT NULL auto_increment,
  `titulo` VARCHAR(45) NOT NULL,
  `aceitacao` VARCHAR(45) NOT NULL,
  `idusuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_roteiro_1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`cpf`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`palavra_chave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`palavra_chave` (
  `id` INT NOT NULL auto_increment,
  `palavra` VARCHAR(45) NOT NULL,
  `sentimento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`localidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`localidade` (
  `id` INT NOT NULL,
  `latitude` VARCHAR(45) NOT NULL,
  `longitude` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tweet` (
  `id` INT NOT NULL,
  `texto` VARCHAR(200) NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `like` TINYINT(1) NOT NULL,
  `idlocalidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_localidade_idx` (`idlocalidade` ASC),
  CONSTRAINT `fk_localidade`
    FOREIGN KEY (`idlocalidade`)
    REFERENCES `mydb`.`localidade` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sentimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sentimento` (
  `id` INT NOT NULL,
  `sentimento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tweet_sentimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tweet_sentimento` (
  `idtweet` INT NOT NULL,
  `idsentimento` INT NOT NULL,
  INDEX `fk_sentimento_idx` (`idsentimento` ASC),
  CONSTRAINT `fk_tweet_sentimento`
    FOREIGN KEY (`idtweet`)
    REFERENCES `mydb`.`tweet` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sentimento`
    FOREIGN KEY (`idsentimento`)
    REFERENCES `mydb`.`sentimento` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tweet_palavrachave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tweet_palavrachave` (
  `idtweet` INT NOT NULL,
  `idpalavrachave` INT NOT NULL,
  INDEX `fk_tweet_idx` (`idtweet` ASC),
  INDEX `fk_palavrachave_idx` (`idpalavrachave` ASC),
  CONSTRAINT `fk_tweet_palavra`
    FOREIGN KEY (`idtweet`)
    REFERENCES `mydb`.`tweet` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_palavrachave`
    FOREIGN KEY (`idpalavrachave`)
    REFERENCES `mydb`.`palavra_chave` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roteiro_palavrachave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roteiro_palavrachave` (
  `idroteiro` INT NOT NULL,
  `idpalavrachave` INT NOT NULL,
  INDEX `fk_roteiro_idx` (`idroteiro` ASC),
  INDEX `fk_palavrachave_idx` (`idpalavrachave` ASC),
  CONSTRAINT `fk_roteiro`
    FOREIGN KEY (`idroteiro`)
    REFERENCES `mydb`.`roteiro` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_palavra`
    FOREIGN KEY (`idpalavrachave`)
    REFERENCES `mydb`.`palavra_chave` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
